name: Build and deploy ASP.Net Core app to Azure Web App - difc-api

on:
  push:
    branches:
      - qa
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      # Restore solution
      - name: Restore dependencies
        run: dotnet restore DIFC-Backend/DIFC.slnx

      # Build solution
      - name: Build
        run: dotnet build DIFC-Backend/DIFC.slnx --configuration Release --no-restore

      # Publish API
      - name: Publish API
        run: dotnet publish DIFC-Backend/DIFC.API/DIFC.API.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'difc-api'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_44D9FEF2D6E6429CAB91392D9BF22417 }}